import type { Product } from "./types"

export const products: Product[] = [
  {
    id: "empanada-papa-pollo",
    name: "Empanada",
    description: "Papa y pollo",
    price: 3500,
    priceWithDrink: 4500,
    image: "/images/empanada.png",
    category: "empanada",
    hasDrinkOption: true,
  },
  {
    id: "pastel-pollo",
    name: "Pastel de Pollo",
    description: "Papa y pollo",
    price: 4000,
    priceWithDrink: 5000,
    image: "/images/pastel.png",
    category: "pastel",
    hasDrinkOption: true,
  },
  {
    id: "arepa-pollo",
    name: "Arepa de Pollo",
    description: "Pollo, tocineta, maicitos, hogao, pico de gallo y salsas",
    price: 15000,
    priceWithDrink: 16000,
    image: "/images/arepa-pollo.png",
    category: "arepa",
    hasDrinkOption: true,
  },
  {
    id: "arepa-carne",
    name: "Arepa de Carne Desmechada",
    description: "Carne desmechada, hogao, platanitos, pico de gallo, guacamole y salsas",
    price: 18000,
    priceWithDrink: 19000,
    image: "/images/arepa-carne.png",
    category: "arepa",
    hasDrinkOption: true,
  },
  {
    id: "arepa-mixta",
    name: "Arepa Mixta",
    description: "Pollo, carne desmechada, hogao, platanitos, guacamole, pico de gallo y salsas",
    price: 19000,
    priceWithDrink: 20000,
    image: "/images/arepa-mixta.png",
    category: "arepa",
    hasDrinkOption: true,
  },
]
